apiVersion: v1
kind: Service
metadata:
  name: cs-service
  labels:
    app: cs-service
spec:
  type: ClusterIP
  selector:
    app: cs-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
